name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: E2E Tests - Chromium
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: lighthouse-app/package-lock.json

      - name: Install dependencies
        working-directory: lighthouse-app
        run: npm ci

      - name: Install Playwright browsers
        working-directory: lighthouse-app
        run: npx playwright install chromium --with-deps

      - name: Build application
        working-directory: lighthouse-app
        run: npm run build

      - name: Run E2E tests
        working-directory: lighthouse-app
        run: npx playwright test --project=chromium
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: lighthouse-app/playwright-report/
          retention-days: 7

      - name: Upload test videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-videos
          path: lighthouse-app/test-results/
          retention-days: 3

  report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload merged report
        uses: actions/upload-artifact@v3
        with:
          name: final-test-report
          path: playwright-report/
          retention-days: 30
